export enum AppPermissions {
    USUARIOS_LIST = 'USUARIOS_LIST',
    GANADO_CREATE = 'GANADO_CREATE',
    GANADO_EDIT = 'GANADO_EDIT',
    GANADO_DELETE = 'GANADO_DELETE',
    ADMIN_ACCESS = 'ADMIN_ACCESS',
    SECRETARY_ACCESS = 'SECRETARY_ACCESS',

}
